/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AccountSearchResultsInfoDTO {
  id?: number;
  name?: string;
  emitterId?: string;
  status?:
    | 'UNAPPROVED'
    | 'DENIED'
    | 'NEW'
    | 'LIVE'
    | 'DEEMED_WITHDRAWN'
    | 'PERMIT_REFUSED'
    | 'AWAITING_SURRENDER'
    | 'SURRENDERED'
    | 'AWAITING_REVOCATION'
    | 'REVOKED'
    | 'AWAITING_TRANSFER'
    | 'TRANSFERRED';
  legalEntityName?: string;
}
