/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AccountUserContact {
  userId?: string;
  Account_type?: string;
  Account_ID?: string;
  Account_name?: string;
  Account_status?: string;
  Permit_ID?: string;
  Permit_type_Account_category?: string;
  Is_User_Primary_contact?: boolean;
  Is_User_Secondary_contact?: boolean;
  Is_User_Financial_contact?: boolean;
  Is_User_Service_contact?: boolean;
  User_status?: string;
  Name?: string;
  Telephone?: string;
  Last_logon?: string;
  Email?: string;
  User_role?: string;
}
