/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AccountAssignedRegulatorSiteContact {
  userId?: string;
  Account_ID?: string;
  Account_type?: string;
  Account_name?: string;
  Account_status?: string;
  User_status?: string;
  Assigned_regulator?: string;
}
