/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountContactVbInfoDTO } from './accountContactVbInfoDTO';

export interface AccountContactVbInfoResponse {
  contacts?: Array<AccountContactVbInfoDTO>;
  editable?: boolean;
  totalItems?: number;
}
