/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Assets } from './assets';
import { CertificateDetails } from './certificateDetails';
import { CertificatesDetails } from './certificatesDetails';
import { EnergyConsumption } from './energyConsumption';
import { EnergySavingsCategories } from './energySavingsCategories';

export interface AlternativeComplianceRoutes {
  totalEnergyConsumptionReduction?: number;
  energyConsumptionReduction?: EnergyConsumption;
  energyConsumptionReductionCategories?: EnergySavingsCategories;
  assets?: Assets;
  iso50001CertificateDetails?: CertificateDetails;
  decCertificatesDetails?: CertificatesDetails;
  gdaCertificatesDetails?: CertificatesDetails;
}
