/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AviationAerSafPurchase {
  fuelName: string;
  batchNumber: string;
  safMass: string;
  sustainabilityCriteriaEvidenceType:
    | 'SCREENSHOT_FROM_RTFO_REGISTRY'
    | 'VOLUNTARY_CERTIFICATION_SCHEME_MARKING'
    | 'FUEL_SUPPLIER_REPORT'
    | 'OTHER';
  otherSustainabilityCriteriaEvidenceDescription?: string;
  evidenceFiles?: Array<string>;
}
