/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AviationRptAirportsDTO {
  icao: string;
  name: string;
  country: string;
  countryType:
    | 'EEA_COUNTRY'
    | 'EEA_DEPENDENT_COUNTRY'
    | 'EFTA_COUNTRY'
    | 'ACCESSION'
    | 'CLOSELY_CONNECTED_TO_EEA_COUNTRY'
    | 'THIRD_COUNTRY'
    | 'UKETS_FLIGHTS_TO_EEA_REPORTED'
    | 'UKETS_FLIGHTS_TO_EEA_NOT_REPORTED';
}
