/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CalculationParameterMeasurementUnits {
  activityDataMeasurementUnit?: 'TONNES' | 'NM3';
  efMeasurementUnit?: 'TONNES_OF_CO2_PER_TJ' | 'TONNES_OF_CO2_PER_NM3' | 'TONNES_OF_CO2_PER_TONNE';
  ncvMeasurementUnit?: 'GJ_PER_TONNE' | 'GJ_PER_NM3';
  carbonContentMeasurementUnit?:
    | 'TONNES_OF_CO2_PER_NM3'
    | 'TONNES_OF_CO2_PER_TONNE'
    | 'TONNES_OF_CARBON_PER_NM3'
    | 'TONNES_OF_CARBON_PER_TONNE';
}
