/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnergyAudit } from './energyAudit';

export interface ComplianceRoute {
  areDataEstimated: boolean;
  areEstimationMethodsRecordedInEvidencePack?: boolean;
  twelveMonthsVerifiableDataUsed?: 'YES' | 'NO' | 'NOT_APPLICABLE';
  energyConsumptionProfilingUsed?: 'YES' | 'NO' | 'NOT_APPLICABLE';
  areEnergyConsumptionProfilingMethodsRecorded?: boolean;
  energyAudits?: Array<EnergyAudit>;
  partsProhibitedFromDisclosingExist: boolean;
  partsProhibitedFromDisclosing?: string;
  partsProhibitedFromDisclosingReason?: string;
}
