/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnergyConsumption } from './energyConsumption';
import { SignificantEnergyConsumption } from './significantEnergyConsumption';

export interface FirstCompliancePeriodDetails {
  organisationalEnergyConsumption: EnergyConsumption;
  significantEnergyConsumptionExists: boolean;
  significantEnergyConsumption?: SignificantEnergyConsumption;
  explanation?: string;
  potentialReductionExists: boolean;
  potentialReduction?: EnergyConsumption;
}
