/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface InventoryEmissionCalculationParamsDTO {
  emissionFactor?: string;
  netCalorificValue?: string;
  oxidationFactor?: string;
  ncvMeasurementUnit?: 'GJ_PER_TONNE' | 'GJ_PER_NM3';
  efMeasurementUnit?: 'TONNES_OF_CO2_PER_TJ' | 'TONNES_OF_CO2_PER_NM3' | 'TONNES_OF_CO2_PER_TONNE';
}
