/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInfoDTO } from './userInfoDTO';

export interface ItemOrganisationDTO {
  creationDate?: string;
  requestId?: string;
  requestType?: 'ORGANISATION_ACCOUNT_OPENING' | 'NOTIFICATION_OF_COMPLIANCE_P3';
  taskId?: number;
  taskAssignee?: UserInfoDTO;
  taskAssigneeType?: 'OPERATOR' | 'VERIFIER' | 'REGULATOR';
  taskType?:
    | 'ORGANISATION_ACCOUNT_OPENING_APPLICATION_REVIEW'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_APPLICATION_SUBMIT'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_APPLICATION_EDIT'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_WAIT_FOR_EDIT';
  daysRemaining?: number;
  accountId?: number;
  accountName?: string;
  competentAuthority?: 'ENGLAND' | 'NORTHERN_IRELAND' | 'OPRED' | 'SCOTLAND' | 'WALES';
  accountOrganisationId?: string;
  accountRegistrationNumber?: string;
  isNew?: boolean;
}
