/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MiReportSearchResult {
  id?: number;
  miReportType?:
    | 'LIST_OF_ACCOUNTS_USERS_CONTACTS'
    | 'COMPLETED_WORK'
    | 'REGULATOR_OUTSTANDING_REQUEST_TASKS'
    | 'LIST_OF_ACCOUNTS_ASSIGNED_REGULATOR_SITE_CONTACTS'
    | 'LIST_OF_VERIFICATION_BODY_USERS'
    | 'CUSTOM';
}
