/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TemplateInfoDTO } from './templateInfoDTO';

export interface NotificationTemplateDTO {
  id?: number;
  name?: string;
  subject?: string;
  text?: string;
  eventTrigger?: string;
  workflow?: string;
  lastUpdatedDate?: string;
  documentTemplates?: Array<TemplateInfoDTO>;
}
