/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactPerson } from './contactPerson';
import { NocP3 } from './nocP3';

export interface NotificationOfComplianceP3ApplicationSubmitRequestTaskPayloadAllOf {
  noc?: NocP3;
  secondaryContact?: ContactPerson;
  nocSectionsCompleted?: { [key: string]: string };
  nocAttachments?: { [key: string]: string };
}
