/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface OrganisationAccountDTO {
  id?: number;
  registrationNumber?: string;
  name: string;
  line1: string;
  line2?: string;
  city: string;
  county: string;
  postcode: string;
  competentAuthority: 'ENGLAND' | 'NORTHERN_IRELAND' | 'OPRED' | 'SCOTLAND' | 'WALES';
  organisationId?: string;
  status?: 'UNAPPROVED' | 'LIVE' | 'DENIED';
}
