/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface OutstandingRequestTask {
  requestTaskAssignee?: string;
  Account_ID?: string;
  Account_type?: 'ORGANISATION';
  Account_name?: string;
  Legal_Entity_name?: string;
  Workflow_ID?: string;
  Workflow_type?: 'ORGANISATION_ACCOUNT_OPENING' | 'NOTIFICATION_OF_COMPLIANCE_P3';
  Workflow_task_name?:
    | 'ORGANISATION_ACCOUNT_OPENING_APPLICATION_REVIEW'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_APPLICATION_SUBMIT'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_APPLICATION_EDIT'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_WAIT_FOR_EDIT';
  Workflow_task_assignee?: string;
  Workflow_task_due_date?: string;
  Workflow_task_days_remaining?: number;
}
