/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankAccountDetailsDTO } from './bankAccountDetailsDTO';
import { RequestTaskPayload } from './requestTaskPayload';

export interface PaymentMakeRequestTaskPayload extends RequestTaskPayload {
  amount?: string;
  paymentRefNum?: string;
  creationDate?: string;
  paymentMethodTypes?: Array<'BANK_TRANSFER' | 'CREDIT_OR_DEBIT_CARD'>;
  bankAccountDetails?: BankAccountDetailsDTO;
  externalPaymentId?: string;
}
