/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PfcEmissionsCalculationDTO {
  globalWarmingPotentialCF4?: string;
  globalWarmingPotentialC2F6?: string;
  amountOfCF4?: string;
  totalCF4Emissions?: string;
  amountOfC2F6?: string;
  totalC2F6Emissions?: string;
  reportableEmissions?: string;
}
