/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestMetadata } from './requestMetadata';

export interface RequestDetailsDTO {
  id?: string;
  requestType?: 'ORGANISATION_ACCOUNT_OPENING' | 'NOTIFICATION_OF_COMPLIANCE_P3';
  requestStatus?:
    | 'IN_PROGRESS'
    | 'COMPLETED'
    | 'CANCELLED'
    | 'WITHDRAWN'
    | 'APPROVED'
    | 'REJECTED'
    | 'CLOSED'
    | 'EXEMPT';
  creationDate?: string;
  requestMetadata?: RequestMetadata;
}
