/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The search criteria
 */
export interface RequestSearchByAccountCriteria {
  accountId: number;
  requestTypes?: Array<'ORGANISATION_ACCOUNT_OPENING' | 'NOTIFICATION_OF_COMPLIANCE_P3'>;
  requestStatuses?: Array<
    'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED' | 'WITHDRAWN' | 'APPROVED' | 'REJECTED' | 'CLOSED' | 'EXEMPT'
  >;
  category: 'PERMIT' | 'REPORTING' | 'CA';
  pageNumber: number;
  pageSize: number;
}
