/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RequestTaskPayload {
  payloadType?:
    | 'ORGANISATION_ACCOUNT_OPENING_APPLICATION_PAYLOAD'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_APPLICATION_SUBMIT_PAYLOAD'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_APPLICATION_EDIT_PAYLOAD'
    | 'RFI_RESPONSE_SUBMIT_PAYLOAD'
    | 'RDE_RESPONSE_SUBMIT_PAYLOAD'
    | 'RDE_WAIT_FOR_RESPONSE_PAYLOAD'
    | 'PAYMENT_MAKE_PAYLOAD'
    | 'PAYMENT_TRACK_PAYLOAD'
    | 'PAYMENT_CONFIRM_PAYLOAD';
}
