/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountStatus } from './accountStatus';

export interface RequestCreateValidationResult {
  valid?: boolean;
  accountStatus?: AccountStatus;
  applicableAccountStatuses?: Array<AccountStatus>;
  requests?: Array<'ORGANISATION_ACCOUNT_OPENING' | 'NOTIFICATION_OF_COMPLIANCE_P3'>;
}
