/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganisationAccountOpeningSubmitApplicationCreateActionPayload } from './organisationAccountOpeningSubmitApplicationCreateActionPayload';
import { ReportRelatedRequestCreateActionPayload } from './reportRelatedRequestCreateActionPayload';
import { RequestCreateActionEmptyPayload } from './requestCreateActionEmptyPayload';

/**
 * The request create action body
 */
export interface RequestCreateActionProcessDTO {
  requestCreateActionType: 'ORGANISATION_ACCOUNT_OPENING_SUBMIT_APPLICATION' | 'NOTIFICATION_OF_COMPLIANCE_P3';
  requestCreateActionPayload:
    | OrganisationAccountOpeningSubmitApplicationCreateActionPayload
    | ReportRelatedRequestCreateActionPayload
    | RequestCreateActionEmptyPayload;
}
