/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RequestTaskActionPayload {
  payloadType?:
    | 'ORGANISATION_ACCOUNT_OPENING_AMEND_APPLICATION_PAYLOAD'
    | 'ORGANISATION_ACCOUNT_OPENING_SUBMIT_DECISION_PAYLOAD'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_SAVE_APPLICATION_SUBMIT_PAYLOAD'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_SEND_TO_EDIT_PAYLOAD'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_SAVE_APPLICATION_EDIT_PAYLOAD'
    | 'RFI_SUBMIT_PAYLOAD'
    | 'RFI_RESPONSE_SUBMIT_PAYLOAD'
    | 'RDE_SUBMIT_PAYLOAD'
    | 'RDE_RESPONSE_SUBMIT_PAYLOAD'
    | 'RDE_FORCE_DECISION_PAYLOAD'
    | 'PAYMENT_MARK_AS_RECEIVED_PAYLOAD'
    | 'PAYMENT_CANCEL_PAYLOAD'
    | 'EMPTY_PAYLOAD';
}
