/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The request task attachment properties
 */
export interface RequestTaskAttachmentActionProcessDTO {
  requestTaskId: number;
  requestTaskActionType:
    | 'ORGANISATION_ACCOUNT_OPENING_AMEND_APPLICATION'
    | 'ORGANISATION_ACCOUNT_OPENING_SUBMIT_DECISION'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_SAVE_APPLICATION_SUBMIT'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_UPLOAD_ATTACHMENT'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_SEND_TO_EDIT'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_SUBMIT_APPLICATION'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_SAVE_APPLICATION_EDIT'
    | 'NOTIFICATION_OF_COMPLIANCE_P3_RETURN_TO_SUBMIT'
    | 'RFI_SUBMIT'
    | 'RFI_UPLOAD_ATTACHMENT'
    | 'RFI_RESPONSE_SUBMIT'
    | 'RFI_CANCEL'
    | 'RDE_SUBMIT'
    | 'RDE_RESPONSE_SUBMIT'
    | 'RDE_FORCE_DECISION'
    | 'RDE_UPLOAD_ATTACHMENT'
    | 'PAYMENT_MARK_AS_PAID'
    | 'PAYMENT_MARK_AS_RECEIVED'
    | 'PAYMENT_PAY_BY_CARD'
    | 'PAYMENT_CANCEL';
}
