/**
 * ESOS API Documentation
 * ESOS API Documentation
 *
 * The version of the OpenAPI document: uk-esos-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VerificationBodyUser {
  userId?: string;
  Verification_body_name?: string;
  Account_status?: string;
  Accreditation_reference_number?: string;
  Is_accredited_for_UK_ETS_Installations?: boolean;
  Is_accredited_for_EU_ETS_Installations_?: boolean;
  Is_accredited_for_UK_ETS_Aviations?: boolean;
  Is_accredited_for_CORSIA?: boolean;
  User_role?: string;
  Name?: string;
  Email?: string;
  Telephone?: string;
  User_status?: string;
  Last_logon?: string;
}
