package uk.gov.esos.api.reporting.noc.phase3.domain.leadassessor;

public enum ProfessionalBodyType {

	ASSOCIATION_OF_ENERGY_ENGINEERS,
	CIBSE_THE_CHARTERED_INSTITUTION_OF_BUILDING_SERVICES_ENGINEERS,
	ELMHURST_ENERGY_SYSTEMS,
	ENERGY_INSTITUTE,
	ENERGY_MANAGERS_ASSOCIATION,
	INSTITUTION_OF_CHEMICAL_ENGINEERS,
	INSTITUTE_OF_ENVIRONMENTAL_MANAGEMENT_AND_ASSESSMENT, 
	QUIDOS,
	STROMA_CERTIFICATION_LTD;
}
