package uk.gov.esos.api.authorization.core.domain;

public enum Permission {

    // Organisation Account Opening Application task
    PERM_ORGANISATION_ACCOUNT_OPENING_APPLICATION_REVIEW_VIEW_TASK,
    PERM_ORGANISATION_ACCOUNT_OPENING_APPLICATION_REVIEW_EXECUTE_TASK,

    // Notification Of Compliance Application task
    PERM_NOTIFICATION_OF_COMPLIANCE_APPLICATION_SUBMIT_VIEW_TASK,
    PERM_NOTIFICATION_OF_COMPLIANCE_APPLICATION_SUBMIT_EXECUTE_TASK,

    PERM_NOTIFICATION_OF_COMPLIANCE_APPLICATION_EDIT_VIEW_TASK,
    PERM_NOTIFICATION_OF_COMPLIANCE_APPLICATION_EDIT_EXECUTE_TASK,
    
    // Organisation Account Opening Archive task
    PERM_ORGANISATION_ACCOUNT_OPENING_ARCHIVE_VIEW_TASK,
    PERM_ORGANISATION_ACCOUNT_OPENING_ARCHIVE_EXECUTE_TASK,
    
    // Permissions for Task Assignment
    PERM_TASK_ASSIGNMENT,
    
    // User management
    PERM_ACCOUNT_USERS_EDIT,
    PERM_CA_USERS_EDIT,

    PERM_VB_ACCESS_ALL_ACCOUNTS,
}
