package uk.gov.esos.api.workflow.request.core.domain.enumeration;

public enum RequestActionPayloadType {
    ORGANISATION_ACCOUNT_OPENING_APPLICATION_SUBMITTED_PAYLOAD,
    ORGANISATION_ACCOUNT_OPENING_DECISION_SUBMITTED_PAYLOAD,

    //Notification of compliance phase 3
    NOTIFICATION_OF_COMPLIANCE_P3_APPLICATION_SENT_TO_EDIT_PAYLOAD,
    NOTIFICATION_OF_COMPLIANCE_P3_APPLICATION_SUBMITTED_PAYLOAD,
    NOTIFICATION_OF_COMPLIANCE_P3_APPLICATION_RETURNED_TO_SUBMIT_PAYLOAD,

    RFI_SUBMITTED_PAYLOAD,
    RFI_RESPONSE_SUBMITTED_PAYLOAD,
    
    RDE_SUBMITTED_PAYLOAD,
    RDE_REJECTED_PAYLOAD,
    RDE_DECISION_FORCED_PAYLOAD,

    PAYMENT_MARKED_AS_PAID_PAYLOAD,
    PAYMENT_MARKED_AS_RECEIVED_PAYLOAD,
    PAYMENT_COMPLETED_PAYLOAD,
    PAYMENT_CANCELLED_PAYLOAD
}
